spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shelterdb}
    username: ${SPRING_DATASOURCE_USERNAME:shelter}
    password: ${SPRING_DATASOURCE_PASSWORD:shelter}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080
