# Generated by Django 6.0.7 on 2026-07-18 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Slobodna', 'Slobodna'), ('U Procesu', 'U Procesu'), ('Udomljena', 'Udomljena')], default='Slobodna', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shelter/images/animals/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FosterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Na čekanju', 'Na čekanju'), ('Prihvaćen', 'Prihvaćen'), ('Odbijen', 'Odbijen')], default='Na čekanju', max_length=20)),
                ('applicant_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('applicant_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('applicant_phone', models.CharField(blank=True, default='', max_length=30)),
                ('applicant_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_deleted', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shelter.animal')),
            ],
        ),
    ]
